name: Run PokerBot Matches

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Manual trigger

jobs:
  
  run:
    runs-on: ubuntu-latest

    steps:
      - run: date -u
      
      - uses: actions/checkout@v3

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Fetch bot DLLs
        run: |
          chmod +x .github/scripts/fetch-dlls.sh
          .github/scripts/fetch-dlls.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate Docker to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Fetch Docker images
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          chmod +x .github/scripts/fetch-images.sh
          .github/scripts/fetch-images.sh

      - name: Run tournament
        run: cd src/TournamentRunner && dotnet run

      - name: Send results
        run: |
          curl -X POST -H "Content-Type: application/json" \
              -H "X-Secret: $MY_SECRET" \
              --data @src/TournamentRunner/results.json \
              https://pokerbotsboras.grgta.xyz/results
        env:
          MY_SECRET: ${{ secrets.RESULTS_SECRET }}
