name: Run PokerBot Matches

on:
  schedule:
    - cron: '0 0 * * *'  # Every night
  workflow_dispatch:      # Manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Fetch bot DLLs
        run: |
          chmod +x .github/scripts/fetch-dlls.sh
          .github/scripts/fetch-dlls.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tournament
        run: dotnet run 
